<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8</TargetFramework>
    <Version>1.3.0</Version>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <None Update="add_winexpext.reg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test-backup%281%29.tar.gz">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test-backup%282%29.tar.gz">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test-backup.tar.gz">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test-copy.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test-rename.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
